arc2nd/CSC480_project

- .gitignore
- requirements.txt
- setup-scripts/01-CreateAndSeedTables.py
Connection string is hard-coded for now. I'm sure we can fix that later. Install Postgres, set up DB according to connection string, run the setup script to test.
> Fixes #6, Created basic table creation/seed scripts

- src/Chore.py
- src/Reward.py
- src/Role.py
- src/app.py
- src/templates/base.html
- src/templates/reward_add.html
- src/templates/rewards.html
> Implement rewards

- src/Chore.py
- src/app.py
- src/templates/chores.html
> Added chore claiming, updated chores template to show claim link

- setup-scripts/01-CreateAndSeedTables.py
- src/Chore.py
- src/Reward.py
- src/Role.py
- src/User.py
- src/app.py
- src/config.py
- src/templates/base.html
- src/templates/chore_add.html
Fixes #24. Reworked the CRUD operations and some routes. Added a few test routes for us to use until we have a formal testing framework going. You can step your debugger through test/[objectname] to see the methods working.
> 24 crud operations

- src/Chore.py
- src/app.py
- src/templates/admin.html
- src/templates/base.html
- src/templates/chore.html
- src/templates/chore_add.html
- src/templates/index.html
- src/templates/reward.html
- src/templates/reward_add.html
- src/templates/user.html
- src/templates/user_add.html
- src/templates/user_login.html
- src/templates/user_logout.html
Fixes #27. Adds basic bootstrap elements. Adds a consistent nav bar, grid, basic form styling. This is a starting point for our front-end design work.
> 27 bootstrap basics

- frontend/scss/mixins.scss
- frontend/scss/style.scss
- src/app.py
- src/config.py
- src/envs.json
- src/templates/admin.html
- src/templates/base.html
- src/templates/chore.html
- src/templates/reward.html
- src/templates/user.html
This is a general cleanup PR. I've added flash messages to our routes, added styled alerts to show the flash messages to the user, changed our print messages to debug log messages, and done some other basic frontend changes.
Here's the flash messages/alerts:
> General cleanup

- frontend/scss/style.scss
- src/app.py
- src/templates/base.html
- src/templates/splash.html
- src/templates/user_logout.html
Fixes #33. Added a splash page, a route for the page, and did some basic styling:
> merge 33-splash-page into master

- src/User.py
- src/app.py
- src/templates/index.html
- src/templates/reward.html
- src/templates/reward_view.html
Fixes #42, creates a single reward view.
> 42 single reward view

- src/app.py
- src/templates/chore.html
- src/templates/chore_view.html
Fixes #41 - Adds a single chore view.
> 41 single chore view

- setup-scripts/01-CreateAndSeedTables.py
- src/app.py
- src/envs.json
- src/templates/chore.html
- src/templates/chore_reassign.html
- src/templates/chore_view.html
- src/templates/index.html
Fixes #47 . Adds the ability to reassign chores, or assign a chore if it is currently unassigned (same page).
> 47 assign chores

- src/Chore.py
- src/app.py
Fixes #51. This changes the way chores are assigned and reassigned. It is a dropdown box instead of a textfield. This is less error-prone as discussed previously. Additionally, I found it necessary to add a Chore.Unassign() method.
> #51 chore add selectfield

- setup-scripts/01-CreateAndSeedTables.py
- src/Chore.py
- src/Recurrence.py
- src/app.py
- src/templates/chore.html
- src/templates/chore_add.html
- src/templates/chore_edit.html
- src/templates/chore_view.html
Fixes #13. Implements a recurrence relation. This adds a new table to the database and creates a relationship between it and the chores table. A new recurrence value is selectable when adding a chore. Right now we have "does not repeat", "daily" and "weekly" as options. I've stored chore frequency values in days in the recurrence so that we can eventually build a script/process that automates creating the recurrences (copying the chores in the database, adding the days to the due date basically).
> 13 recurrence relation

- src/templates/base.html
- src/templates/user.html
- src/templates/user_edit.html
Fixes #61 - Added user edit links.
> 61 user edit links

- src/BaseMixin.py
- src/ErrorHandler.py
- src/User.py
- src/_unittests.py
- src/app.py
- src/config.py
- src/envs.json
- src/templates/error.html
Fixes #64. Adds unittest library, sample unit test for User object, generic error handler for catching exceptions and handing them to a flask view.
> 64 unit tests

- src/app.py
- src/envs.json
- src/templates/chore_view.html
- src/templates/reward_view.html
Fixes #69, fixes access and action links on chore/reward views.
> 69 chore reward access

- src/envs.json
- src/templates/user_reset_password.html
> 71 reset password button

- package.json
- src/Chore.py
- src/Log.py
- src/envs.json
Fixes #68. Can you take a look at this idea and tell me what you think? I've added the chore recurrence creation step to the complete chore method. I think this could be a simple solution.
> 68 recurring chores

- src/Chore.py
- src/Log.py
- src/notifications.py
- src/reminder_html.txt
- src/reminder_text.txt
built a notifications script. Don't have a localhost smtp but I ran it with the Debugging server: 'python -m smtpd -n -c DebuggingServer localhost:1025' and everything worked
> 76 notifications

- src/app.py
> #80 - Fixes session-related errors

- src/Chore.py
- src/User.py
- src/app.py
- src/envs.json
Fixes #88. Unassigns chores before deleting a user.
> #88 - Unassign chores before deleting a user

- src/app.py
- src/envs.json
Fixes #92. Implements a uniqueness check for reward names.
> 92 unique reward

- frontend/js/scripts.js
- frontend/scss/style.scss
- src/app.py
- src/envs.json
- src/templates/base.html
- src/templates/chore.html
- src/templates/reward.html
Fixes #95. Adds a confetti/rainbow button to the complete chore/claim reward pages. Try completing a chore or claiming a reward to see. Click the button to start, click it again to stop.
Need to run another "gulp min" to get these changes after you pull the branch down. Make sure you do a hard refresh in your browser too to clear the cached js/css (CTRL+F5).
> #95 - Added a confetti effect to completing chores, claiming rewards
